import { AppContainer } from './globalStyles'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AppContainer>
        <div className={inter.className}>
          <nav>
            <div style={{ display: "flex", justifyContent: "space-between" }}>
              <div>andrewpethoud.dev</div>
              <div style={{ display: "flex" }}>
                <div>Blog</div>
                <div>Projects</div>
              </div>
            </div>
          </nav>
          <div style={{ display: "flex", justifyContent: "center" }}>
            {children}
          </div>
        </div>
      </AppContainer>
    </html>
  )
}
