import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <div style={{ display: "flex", justifyContent: "space-between" }}>
            <div>andrewpethoud.dev</div>
            <div style={{ display: "flex" }}>
              <div>Blog</div>
              <div>Projects</div>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  )
}
